import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/general/Navbar";
import Footer from "@/components/general/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "AxisPoint",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.ico" sizes="32x32" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased 
          max-w-8xl mx-auto min-h-screen flex flex-col`}
        >

<div className="sticky top-0 left-0 w-full bg-[#001f3f] px-4 sm:px-6 lg:px-8 shadow-md z-50">
  <Navbar />
</div>

          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </html>
  );
}
